final List<Map<String, dynamic>> products = [
  {
    'id': '0',
    'title': "Nike Air Force 1 High",
    'price': 123.74,
    'imageUrl': 'assets/images/nike1.png',
    'company': 'Nike',
    'sizes': [09, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Nike LeBron 21 Premium',
    'price': 58.12,
    'imageUrl': 'assets/images/nike2.png',
    'company': 'Nike',
    'sizes': [08, 10, 12],
  },
  {
    'id': '2',
    'title': 'Adidas Racer TR23 Shoes',
    'price': 62.10,
    'imageUrl': 'assets/images/adidas1.png',
    'company': 'Adidas',
    'sizes': [07, 08, 09, 10],
  },
  {
    'id': '3',
    'title': 'Air Jordan 4 Retro',
    'price': 78.99,
    'imageUrl': 'assets/images/nike3.png',
    'company': 'Nike',
    'sizes': [08, 09, 10, 11],
  },
  {
    'id': '4',
    'title': 'Puma Spirex IOS',
    'price': 78.45,
    'imageUrl': 'assets/images/puma2.png',
    'company': 'Puma',
    'sizes': [08, 09, 10, 13],
  },
  {
    'id': '5',
    'title': 'Nike Air Max 90 Drift',
    'price': 97.50,
    'imageUrl': 'assets/images/nike4.png',
    'company': 'Nike',
    'sizes': [07, 08, 12, 13],
  },
  {
    'id': '6',
    'title': 'Puma Clyde Hairy Suede Sneaker',
    'price': 48.00,
    'imageUrl': 'assets/images/puma1.png',
    'company': 'Puma',
    'sizes': [07, 08, 09, 11, 12],
  },
  {
    'id': '7',
    'title': 'Bata REMON Men\'s Casual Loafer',
    'price': 38.78,
    'imageUrl': 'assets/images/bata1.png',
    'company': 'Bata',
    'sizes': [08, 10, 11, 13],
  },
  {
    'id': '8',
    'title': 'Puma x Fenty Creeper Phatty',
    'price': 93.69,
    'imageUrl': 'assets/images/puma3.png',
    'company': 'Puma',
    'sizes': [08, 09, 11, 10],
  },
  {
    'id': '9',
    'title': 'Bata SHELDON Casual Sneaker',
    'price': 62.12,
    'imageUrl': 'assets/images/bata2.png',
    'company': 'Bata',
    'sizes': [07, 09, 11, 12],
  },
  {
    'id': '10',
    'title': 'Adidas Swift Run Shoes',
    'price': 37.85,
    'imageUrl': 'assets/images/adidas2.png',
    'company': 'Adidas',
    'sizes': [08, 09, 10, 11, 13],
  },
];

final List<Map<String, dynamic>> carts = [];
