import 'dart:ui';

final List<Map<String, dynamic>> products = [
  {
    'id': '0',
    'title': "Nike Jordan Shoes",
    'price': 44.52,
    'imageUrl': 'assets/images/nike1.png',
    'color': const Color(0xFF003366).withOpacity(0.1),
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Women\'s Nike Shoes',
    'price': 58.12,
    'imageUrl': 'assets/images/nike2.png',
    'color': const Color(0xFF669900).withOpacity(0.1),
    'company': 'Nike',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Adidas Running Shoes',
    'price': 55.10,
    'imageUrl': 'assets/images/adidas1.png',
    'color': const Color(0xFFCC9900).withOpacity(0.1),
    'company': 'Adidas',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Adidas Casual Shoes',
    'price': 34.50,
    'imageUrl': 'assets/images/adidas2.png',
    'color': const Color(0xFF0099CC).withOpacity(0.1),
    'company': 'Adidas',
    'sizes': [6, 7, 8, 9],
  },
  {
    'id': '4',
    'title': 'Nike Classic Shoes',
    'price': 78.45,
    'imageUrl': 'assets/images/nike3.png',
    'color': const Color(0xFFc5c3c1).withOpacity(0.1),
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '5',
    'title': 'Nike Sports Shoes',
    'price': 97.50,
    'imageUrl': 'assets/images/nike4.png',
    'color': const Color(0xFFA020F0).withOpacity(0.1),
    'company': 'Nike',
    'sizes': [7, 8, 9],
  },
  {
    'id': '6',
    'title': 'Puma Casual Shoes',
    'price': 34.50,
    'imageUrl': 'assets/images/puma1.png',
    'color': const Color(0xFF00CC99).withOpacity(0.1),
    'company': 'Puma',
    'sizes': [6, 7, 8, 9, 11],
  },
  {
    'id': '7',
    'title': 'Puma Classic Shoes',
    'price': 78.45,
    'imageUrl': 'assets/images/puma2.png',
    'color': const Color(0xFFCC6699).withOpacity(0.1),
    'company': 'Puma',
    'sizes': [8, 9, 10],
  },
  {
    'id': '8',
    'title': 'Puma Sports Shoes',
    'price': 97.50,
    'imageUrl': 'assets/images/puma3.png',
    'color': const Color(0xFF6699CC).withOpacity(0.1),
    'company': 'Puma',
    'sizes': [7, 8, 9],
  },
];

final List<Map<String, dynamic>> carts = [];
